### ISSUE TITLE
babel 6 peer-dependencies

### ISSUE THREAD

**Issue by parro-it** [hax/babel-features#10]
Hi, I wrote [eslint-config-features](https://github.com/parro-it/eslint-config-features) a module that uses `babel-features` to convert babel rules to eslint rules. 
It provide an es lint config that provide dynamic configured `ecmaFeature` set based on node version in use.
It work well even for packaged which not use babel, but your module contains a peer-depencies on babel, so every time you install my module, there is an annoying  warning message to install babel6.
I'm asking you if you are ok in removing this peer-depencies from babel-features. I could write a PR

**Comment by ariporad** [comment]
Sure, I'll remove it.

**Comment by ariporad** [comment]
Whoops... Wrong repo. Never mind.

**Comment by parro-it** [comment]
ping @hax

**Comment by parro-it** [comment]
Thank you!

**Comment by hax** [comment]
@parro-it Sorry, I just took a very long vacation these days :smiley_cat:

**Comment by parro-it** [comment]
No worries @hax! Thank you again!
