### ISSUE TITLE
I turned this into a preset!

### ISSUE THREAD

**Issue by ariporad** [hax/babel-features#5]
Hi @hax!

Thanks for making this such an awesome module! I just wanted to let you know that I wrote a really thin wrapper around this to turn it into a babel preset! It's on npm as [babel-preset-features](npm.im/babel-preset-features). This way you can just install it and use it via your `.babelrc`:

``` json
{
    "presets": ["feature"]
}
```

**Comment by hax** [comment]
Cool! I will update the README.
