### ISSUE TITLE
Include babel-preset-es2015 as a dependency

### ISSUE THREAD

**Issue by ariporad** [hax/babel-features#6]
Hi!

Just so you know, in the 2.x branch, you probably want to include babel-preset-es2015 as a dependency (or maybe a peerDependency), so that all the transformers will be available to require. Otherwise, the user has to install that manually, which is confusing.

Enjoy!

**Comment by hax** [comment]
This package is only for generate options, so `babel-preset-*` or `babel-plugins-*` are not required as dependencies.

**Comment by ariporad** [comment]
@hax: I know, but it would be intuitive to not have to include anything else as a dependency. (Or at least document that you do)

**Comment by hax** [comment]
@ariporad I notice that your `babel-preset-features` already have the `babel-plugins-*` as deps and I think it's the better way. About document, PR is welcomed :grinning:

**Comment by hax** [comment]
I just release the 2.0.0 which is totally rewritten. Now `babel-preset-es2015` has been included in the devDeps.
